baseUrl = "ngundotra.github.io"
languageCode = "en-us"

title = "Noah Gundotra"
theme = "hugo-coder"
defaultcontentlanguage = "en"

[params]
  author = "Noah Gundotra"
  info = "Quant and Deep Learning Engineer"
  description = "Noah Gundotra's personal website"
  keywords = "blog,developer,personal"

  colorsheme = "auto"
  hidecolorschemetoggle = false


# Social links
[[params.social]]
  name = "Github"
  icon = "fa fa-github fa-2x"
  weight = 1
  url = "https://github.com/ngundotra/"
[[params.social]]
  name = "Twitter"
  icon = "fa fa-twitter fa-2x"
  weight = 3
  url = "https://twitter.com/ngundotra/"

# Menu links
[[menu.main]]
  name = "Research"
  weight = 1
  url  = "research/"
[[menu.main]]
  name = "About"
  weight = -1
  url = "about/"
[[menu.main]]
  name = "Blog"
  weight = 69
  url = "posts/"

